language: python
python:
  - "3.8.5"

# Install dependencies.
install:
  - pip install -r requirements.txt
  - pip install flake8

# Run linting and tests.
script:
  - pylint ./src
  - flake8 ./src --statistics --count
  - pytest

# Turn email notifications off.
notifications:
  email: false
